### ISSUE TITLE
`upsert` for `Map`

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-ordered-collections#13]
If we were going to add this, of the following two versions, which would you prefer?

``` purescript
upsert :: forall k v. Ord k => (v -> v) -> k -> v -> Map k v -> Map k v
upsert f k v = Map.alter (Just <<< maybe v f) k
```

``` purescript
upsert' :: forall k v. Ord k => (v -> v -> v) -> k -> v -> Map k v -> Map k v
upsert' f k v = Map.alter (Just <<< maybe v (f v)) k
```

@kRITZCREEK likes the first version, I prefer the second. 

In my experience it seems more common that you want to update an existing value by doing something with it along with the value you would otherwise be inserting.

Examples:

``` purescript
accumSemigroups = foldr (uncurry (\k v -> upsert (append v) k v)) mempty
countOccurences = foldr (\v -> upsert (_ + 1) v 1) Map.empty
duplicates = Array.filter snd <<< Map.toUnfoldable <<< foldr (\v -> upsert (const true) v false) Map.empty
```

``` purescript
accumSemigroups' = foldr (uncurry (upsert' append)) mempty 
countOccurences' = foldr (\v -> upsert' (+) v 1) Map.empty
duplicates' = Array.filter snd <<< Map.toUnfoldable <<< foldr (\v -> upsert' (\_ _ -> true) v false) Map.empty
```

`duplicates` vs `duplicates'` being the one case where the non-primed `upsert` is slightly more natural, but it's still ignoring an argument so 🤷‍♂️

**Comment by fehrenbach** [comment]
FWIW, -unordered-collections has
```PureScript
insertWith :: forall k v. Hashable k => (v -> v -> v) -> k -> v -> HashMap k v -> HashMap k v
```
and it calls the function with the *existing* value as the first argument.
```PureScript
insertWith (<>) 5 "b" (singleton 5 "a") == singleton 5 "ab"
```

**Comment by garyb** [comment]
I think that's what we'll do - go with `insertWith` for my thing, and add `upsert` too as Christoph's version.

**Comment by garyb** [comment]
Because I'm a genius I just pushed this to master rather than the branch I made it in for some reason. 67a0263f8b1009a26397a811da300f0ef16813c4

I used the same wording as your `insertWith` for the doc comment @fehrenbach, hope that's ok 🙂

**Comment by fehrenbach** [comment]
Yeah, sure!

(I also failed at pushing to a remote branch when adding `upsert` to -unordered-collections :D)

**Comment by kritzcreek** [comment]
This function exists now.
