### ISSUE TITLE
Change union to be right-biased

### ISSUE THREAD

**Issue by fehrenbach** [purescript/purescript-ordered-collections#2]
I'd quite like this to hold:
```PureScript
fromFoldable (a <> b) == fromFoldable a <> fromFoldable b
```

`fromFoldable` is repeated insertion by `foldl`. I assume the reason is to match Haskell's `fromList` which uses `foldl'`, which makes sense for lists.
`(<>)` is `union` is `unionWith const` and that simple implementation seems to be the only reason (and Haskell does it that way).

What do people think?

**Comment by LiamGoodacre** [comment]
My thoughts on this are that I'd rather either not have a direct Semigroup instance or pick `(Ord k, Semigroup v) => Semigroup (Map k v)` (which, I feel, is a more obvious instance).  Then let newtypes deal with the `First`/`Last` behaviour.  In a similar way that we don't pick an instance for `Int` when there are multiple useful interpretations.

**Comment by fehrenbach** [comment]
Good point.

I'm not sure I agree with the "more obvious" part, but still, good point.

I quite like using `foldMap (\x -> singleton (f x) x)` to index an array which would not work without/with a different Semigroup instance. That's not a good argument against, though. That's an argument for `fromFoldableBy` or something.

**Comment by natefaubion** [comment]
This is a 👎 for me. Left-biased union is pretty much standard everywhere in our ecosystem, including `Prim.Row.Union`, for better or worse. We have so much code at work that depends on the union ordering. I would be ambivalent about the `Semigroup` changes with `coerce` and if we had type applications.

**Comment by LiamGoodacre** [comment]
(Side note: I wouldn't describe `Prim.Row.Union` as left-biased.  It acts more like `unionWith (++)` - treating a row effectively as a `Map String (Array Type)` - multiple entries for the same key are preserved left to right.)

**Comment by natefaubion** [comment]
It is effectively left-biased when paired with `Nub`, which is very common. `Nub` technically has the bias, but the behavior of Nub is also consistent (keep the first, ie left-biased value).

This has more of an effect with `Record`, which is that the first (left-most) type for a row is the actual runtime value.

**Comment by LiamGoodacre** [comment]
I thought a record type with duplicates keys was uninhabited.

**Comment by natefaubion** [comment]
No, you can get duplicate labels via `union`. Record delete and insert are just predicated on `Lacks` constraints, and you can't construct a record literal that's typed as having duplicate labels.

**Comment by hdgarrood** [comment]
I’m going to close this, see https://github.com/purescript/purescript-ordered-collections/pull/4#issuecomment-748694038
