### ISSUE TITLE
Sets difference calculation is broken.

### ISSUE THREAD

**Issue by mstream** [purescript/purescript-ordered-collections#67]
It looks like since [this commit](https://github.com/purescript/purescript-ordered-collections/commit/85ee3ba4aab99053e3225044549461d024263923) difference calculation is not working as expected.

Example:
```purescript
S.difference (S.fromFoldable [1,2,3,4]) (S.fromFoldable [2,3]) == S.empty
```

Whereas the above expression should equal to `S.fromFoldable [1,4]`
In fact, I could not find any other inputs that would not yield the empty set for this operation.

Previous versions of that library give expected results.

**Comment by natefaubion** [comment]
Does the test not test what we think it does?
https://github.com/purescript/purescript-ordered-collections/blob/93f3595b4219b4ea973b7669cec72c6a2ee0aaaa/test/Test/Data/Map.purs#L251-L255

**Comment by natefaubion** [comment]
I can confirm that `difference` is broken, but the tests still pass. In the example above `d` has empty keys, and so both predicates are trivially true. The test as written relies on `d` being non empty.
