### ISSUE TITLE
Add `Functor` instances to `NonEmptySet` and `Set`

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-ordered-collections#69]
Just hit this issue. No idea why it doesn't have it. Likely an oversight.

**Comment by garyb** [comment]
Sets can't be `Functor`, it's not law abiding - that's why there's a dedicated `map`.

**Comment by JordanMartinez** [comment]
Ah, because you could map two things to the same thing? I see...

**Comment by garyb** [comment]
Yeah exactly, you can change the structure during the map - mapping multiple things to the same value, `map (const unit)`, etc. :+1:

**Comment by natefaubion** [comment]
> Sets can't be Functor, it's not law abiding - that's why there's a dedicated map.

More than that, it can't be written at all given the definition of `Functor` as you need an `Ord` constraint.

**Comment by JordanMartinez** [comment]
Oh, good point.

**Comment by JordanMartinez** [comment]
Anyways, I wanted to use `partition` from `Filterable`, and and the error I got was that `NonEmptySet` didn't have a `Functor` instance.

**Comment by natefaubion** [comment]
`Filterable` will have the same issue. Their signatures require one to be parametric over the element type, but you can't build new Sets without an Ord constraint.
